# Generated by Django 3.2.4 on 2021-07-03 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comercio_KAA', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tienda',
        ),
    ]
