# Generated by Django 3.2.4 on 2021-07-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comercio_KAA', '0006_auto_20210704_0533'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='descripcion',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
