# Generated by Django 3.2.4 on 2021-07-05 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comercio_KAA', '0010_producto_en_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.FloatField(help_text='Precio en pesos argentinos (AR$)'),
        ),
    ]
