# Generated by Django 3.2.4 on 2021-07-06 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comercio_KAA', '0017_producto_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='slug',
        ),
    ]
